from autodoc.github.github_client import GithubClient


class PRManager:

    def __init__(self):

        self.client = GithubClient()

    async def find_open_pr(
        self,
        github_repo: str,
        review_branch: str,
    ):

        prs = await self.client.get(
            f"/repos/{github_repo}/pulls"
            f"?state=open"
            f"&head={github_repo.split('/')[0]}:{review_branch}"
        )

        if prs:
            return prs[0]

        return None

    async def create_pr(
        self,
        github_repo: str,
        review_branch: str,
    ):

        return await self.client.post(
            f"/repos/{github_repo}/pulls",
            {
                "title": f"AutoDoc improvements: {review_branch}",
                "head": review_branch,
                "base": "main",
                "body": "Automatically generated by AutoDoc.",
            },
        )
