from autodoc.github.github_client import GithubClient


class PRManager:
    """Manages pull requests for GitHub repositories."""

    def __init__(self):
        """Initializes the PRManager with a GitHub client."""
        self.client = GithubClient()

    async def find_open_pr(
        self,
        github_repo: str,
        review_branch: str,
    ) -> dict | None:
        """
        Finds an open pull request for the given repository and branch.

        Args:
            github_repo: The GitHub repository in the format "owner/repo".
            review_branch: The branch name to search for.

        Returns:
            The first open PR if found, otherwise None.
        """
        url = (
            f"/repos/{github_repo}/pulls"
            f"?state=open"
            f"&head={github_repo.split('/')[0]}:{review_branch}"
        )
        prs = await self.client.get(url)
        return prs[0] if prs else None

    async def create_pr(
        self,
        github_repo: str,
        review_branch: str,
        file_path: str,
    ) -> dict:
        """
        Creates a new pull request.

        Args:
            github_repo: The GitHub repository in the format "owner/repo".
            review_branch: The branch name for the pull request.
            file_path: The file path used in the PR title.

        Returns:
            The created PR data from the GitHub API.
        """
        owner = github_repo.split('/')[0]
        payload = {
            "title": f"[AutoDoc] {file_path}",
            "head": f"{owner}:{review_branch}",
            "base": "main",
            "body": "Automatically generated by AutoDoc.",
        }
        return await self.client.post(f"/repos/{github_repo}/pulls", payload)

    async def find_open_pr_for_file(
        self,
        github_repo: str,
        file_path: str,
    ) -> dict | None:
        """
        Finds an open pull request with a title matching the given file path.

        Args:
            github_Repo: The GitHub repository in the format "owner/repo".
            file_path: The file path used in the PR title.

        Returns:
            The matching PR if found, otherwise None.
        """
        url = f"/repos/{github_repo}/pulls?state=open"
        prs = await self.client.get(url)
        title = f"[AutoDoc] {file_path}"
        for pr in prs:
            if pr.get("title") == title:
                return pr
        return None

    async def find_pr_by_number(
        self,
        github_repo: str,
        pr_number: int,
    ) -> dict | None:
        """
        Finds a pull request by its number.

        Args:
            github_repo: The GitHub repository in the format "owner/repo".
            pr_number: The pull request number.

        Returns:
            The PR data if found, otherwise None.
        """
        try:
            return await self.client.get(f"/repos/{github_repo}/pulls/{pr_number}")
        except Exception:
            return None